### ISSUE TITLE
Stop responding to bots

### ISSUE THREAD

**Issue by duncte123** [SophisticaSean/meme_coin#48]
I don't know if this is important to you, but people can use bot accounts to get more memes (see attachment)
![screenshot_20171125-083849](https://user-images.githubusercontent.com/8843386/33228448-4fddda80-d1bc-11e7-9012-1e4215fb3fb2.jpg)

**Comment by SophisticaSean** [comment]
Kind of but not really. Its how some people wanna play. I'd recommend starting a server that disallows bots if you'd like to stay pure. Use !invite to get invite code for bot.
