### ISSUE TITLE
Adding a warning to the 1 day tip ban

### ISSUE THREAD

**Issue by Alchemis-tt** [SophisticaSean/meme_coin#57]
So i noticed that once you tip too many memes to one person, they get a one day ban. Usually there is thought to be no harm in tipping memes, so an innocent person might tip too many memes and be banned without warning. This feels really bad and seems to come out of nowhere (especially since this feature wasn't here before), so perhaps you could add a warning that they are tipping too many memes before getting the ban hammer. thanks.

**Comment by Tyson-Chicken-Nuggets** [comment]
don't get rid of !tip, but do add a warning for the ban please

**Comment by SophisticaSean** [comment]
fixed
