### ISSUE TITLE
Banned for 1000 days

### ISSUE THREAD

**Issue by Kiriot22** [SophisticaSean/meme_coin#59]
![unknown-19](https://user-images.githubusercontent.com/9750071/56869760-f8514580-6a04-11e9-85e2-ab4eeaf8fbe6.png)
Meanie

**Comment by Kikitob** [comment]
![Discord_2019-04-30_17-14-12](https://user-images.githubusercontent.com/30052334/56972548-79c2e800-6b6b-11e9-9057-f20412cbc929.png)
Also happened to me please fix

**Comment by SophisticaSean** [comment]
don't cheat
